#!/bin/bash

# 自动生成的文件命名修复脚本
# 执行前请确保代码已提交到Git

git mv "frontend/components/shared/index.tsx" "frontend\components\shared\Index.tsx"
git mv "frontend/pages/index.tsx" "frontend\pages\Index.tsx"
git mv "frontend/types/axios.d.ts" "frontend\types\请参考命名规范手动修复"
git mv "frontend/types/browser.d.ts" "frontend\types\请参考命名规范手动修复"
git mv "docs/api/services/BaseService.md" "docs\api\services\base-service.md"
git mv "docs/api/services/HTMLParsingService.md" "docs\api\services\h-t-m-l-parsing-service.md"
git mv "docs/CHANGELOG_2025-08-15.md" "docs\c-h-a-n-g-e-l-o-g_2025-08-15.md"
git mv "docs/fixes/404_ERROR_FIX_REPORT.md" "docs\fixes\404_-e-r-r-o-r_-f-i-x_-r-e-p-o-r-t.md"
git mv "docs/guides/README-unified-engine.md" "docs\guides\r-e-a-d-m-e-unified-engine.md"
git mv "docs/intelligent-system/README-INTELLIGENT-SYSTEM.md" "docs\intelligent-system\r-e-a-d-m-e--i-n-t-e-l-l-i-g-e-n-t--s-y-s-t-e-m.md"
git mv "docs/MCP-DETAILED-CONFIG-GUIDE.md" "docs\m-c-p--d-e-t-a-i-l-e-d--c-o-n-f-i-g--g-u-i-d-e.md"
git mv "docs/MCP-INTELLIGENT-USAGE-STRATEGY.md" "docs\m-c-p--i-n-t-e-l-l-i-g-e-n-t--u-s-a-g-e--s-t-r-a-t-e-g-y.md"
git mv "docs/MCP-QUICK-START-GUIDE.md" "docs\m-c-p--q-u-i-c-k--s-t-a-r-t--g-u-i-d-e.md"
git mv "docs/MCP-TOOLS-INTRODUCTION.md" "docs\m-c-p--t-o-o-l-s--i-n-t-r-o-d-u-c-t-i-o-n.md"
git mv "docs/MCP-TROUBLESHOOTING-GUIDE.md" "docs\m-c-p--t-r-o-u-b-l-e-s-h-o-o-t-i-n-g--g-u-i-d-e.md"
git mv "docs/QUICK-START-GUIDE.md" "docs\q-u-i-c-k--s-t-a-r-t--g-u-i-d-e.md"
git mv "docs/reports/current/Test-Web项目重复功能和不一致内容分析报告.md" "docs\reports\current\test--web项目重复功能和不一致内容分析报告.md"
git mv "ENCODING-FIX-CHANGELOG.md" "e-n-c-o-d-i-n-g--f-i-x--c-h-a-n-g-e-l-o-g.md"
git mv "FILE-NAMING-ANALYSIS.md" "f-i-l-e--n-a-m-i-n-g--a-n-a-l-y-s-i-s.md"
git mv "SERVICE-DUPLICATION-ANALYSIS.md" "s-e-r-v-i-c-e--d-u-p-l-i-c-a-t-i-o-n--a-n-a-l-y-s-i-s.md"
git mv "tools/electron/node_modules/date-fns/docs/gettingStarted.md" "tools\electron\node_modules\date-fns\docs\getting-started.md"
git mv "tools/electron/node_modules/date-fns/docs/i18nContributionGuide.md" "tools\electron\node_modules\date-fns\docs\i18n-contribution-guide.md"
git mv "tools/electron/node_modules/date-fns/docs/timeZones.md" "tools\electron\node_modules\date-fns\docs\time-zones.md"
git mv "tools/electron/node_modules/date-fns/docs/unicodeTokens.md" "tools\electron\node_modules\date-fns\docs\unicode-tokens.md"
git mv "tools/electron/node_modules/date-fns/docs/upgradeGuide.md" "tools\electron\node_modules\date-fns\docs\upgrade-guide.md"
