apiVersion: v1
kind: ConfigMap
metadata:
  name: testweb-config
  namespace: testweb
  labels:
    app: testweb
data:
  # Application configuration
  NODE_ENV: "production"
  LOG_LEVEL: "info"
  MONITORING_ENABLED: "true"
  
  # Frontend configuration
  FRONTEND_URL: "https://testweb.app"
  
  # Email configuration
  EMAIL_SERVICE: "smtp"
  EMAIL_PORT: "587"
  
  # Webhook configuration
  WEBHOOK_ENABLED: "true"
  
  # Cache configuration
  CACHE_TTL: "300"
  CACHE_MAX_SIZE: "100"
  
  # Security configuration
  CORS_ORIGIN: "https://testweb.app"
  RATE_LIMIT_MAX: "100"
  RATE_LIMIT_WINDOW: "900000"
  
  # Test engine configuration
  MAX_CONCURRENT_TESTS: "10"
  TEST_TIMEOUT: "300000"
  
---
apiVersion: v1
kind: Secret
metadata:
  name: testweb-secrets
  namespace: testweb
  labels:
    app: testweb
type: Opaque
stringData:
  # Database secrets
  db-host: "postgres-service"
  db-name: "testweb"
  db-user: "testweb"
  db-password: "change-me-in-production"
  
  # JWT secret
  jwt-secret: "your-super-secret-jwt-key-change-in-production"
  
  # Redis password
  redis-password: "change-me-in-production"
  
  # Email configuration
  email-host: "smtp.gmail.com"
  email-user: "your-email@gmail.com"
  email-password: "your-email-password"
  
  # Webhook secret
  webhook-secret: "your-webhook-secret"
  
  # External API keys
  github-token: "ghp_your_github_token"
  gitlab-token: "glpat_your_gitlab_token"
